### ISSUE TITLE
Is there a way to set font size?

### ISSUE THREAD

**Issue by IllustratedMan-code** [fdehau/tui-rs#394] opened 2020-10-07 14:38 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to set font sizes within a paragraph so that I could have smalltextBIGTEXTsmalltext or the like. For example: I am working on a periodic table app and I want the element name to be in smaller font than the numbers.

**Describe the solution you'd like**
I want to change font size, ideally within a single block of text.

**Describe alternatives you've considered**
I don't think there are any alternatives in my project that would not compromise the style that I have intended.

**Additional context**
Here is an example image of the kind of formatting I would want. Is this possible with tui-rs?
![image](https://user-images.githubusercontent.com/60514384/95345845-3359d880-0889-11eb-9d13-a7821623cf48.png)

**Comment by fdehau** [comment] 2020-11-14 19:33
Duplicate of #402

**Closed by fdehau** 2020-11-14 19:33 UTC
Labels: enhancement
