### ISSUE TITLE
TUI does not render properly

### ISSUE THREAD

**Issue by Lubits** [fdehau/tui-rs#56] opened 2018-05-24 15:18 UTC
I tried running the demo, however, the resulting render seems off. Most notably the bar charts. I've tried using terminal and iterm. Any idea what the issue is?

I'm using Rust 1.26.0

![screen shot 2018-05-24 at 17 14 13](https://user-images.githubusercontent.com/3738747/40494915-4b88ec52-5f76-11e8-92c2-570f059e79f5.png)

**Comment by fdehau** [comment] 2018-05-25 05:45
Hum, I've tested `tui` on several terminal configurations when I've first released the crate. Some terminals render better than other but I've never seen a problem like this. The symbols that seem to be incorrectly displayed are the ones defined in [symbols](https://github.com/fdehau/tui-rs/blob/master/src/symbols.rs). Do you use by any chance a patched font ? Could you share your terminal configuration (terminal + font + terminal multiplexer if any) ?

**Comment by Lubits** [comment] 2018-05-25 08:51
I do have some patched fonts installed, but they are (I think) not being used.
I've tried some different fonts in with the same results (Monaco, Inconsolata, Consolas, Menlo) using Terminal 2.8.2, iTerm2 3.1.6 and some version of Alacritty which I can't find.

Normally I don't use any terminal multiplexer, I've tried running it using iterm2+tmux too, with the same results.

**Comment by karolinepauls** [comment] 2018-11-26 23:55
I can reproduce this on Kubuntu (Ubuntu 18.04.1 LTS) in Konsole (konsole 17.12.3).

![image](https://user-images.githubusercontent.com/43616133/49049393-b5c9d980-f1d6-11e8-9c32-304c8158620c.png)

**Comment by fdehau** [comment] 2018-12-04 08:12
@karolinepauls What font are you using in the previous screenshot ?

**Comment by karolinepauls** [comment] 2018-12-04 12:53
Liberation Mono was selected but it seems like Konsole lies about the font. Switching to something else and then "back" to Liberation Mono helped a bit. The actual font in use seems to be Ubuntu Mono (switching to it reproduces the issues.

Looks like Ubuntu Mono either defines the bar characters as wider than it should or doesn't define them and they're taken from anther font.

![image](https://user-images.githubusercontent.com/43616133/49442828-91679180-f7c2-11e8-9e39-92712a8c97f0.png)
Only the first one (█ \u2588) appears to be the right height.

For reference:
```
In [16]: for c in chars: print(c, c.encode('unicode-escape').decode('ascii'))
█ \u2588
▇ \u2587
▆ \u2586
▅ \u2585
▄ \u2584
▃ \u2583
▂ \u2582
▁ \u2581
```

**Comment by karolinepauls** [comment] 2018-12-04 13:58
I don't think it's generally safe do display anything non-ASCII. In a raw TTY almost all special characters from the "block" and "bar" categories (except for FULL) are replaced by an escape. This is easy to see if you simply `cat` src/symbol.rs in a TTY.

**Comment by karolinepauls** [comment] 2018-12-08 13:10
https://bugs.launchpad.net/ubuntu/+source/fontconfig/+bug/932958

**Comment by fdehau** [comment] 2020-04-14 17:19
#264 added the possibility to choose a different set of symbols for the `BarChart` and `Sparkline` widgets. In particular, you can choose to render using only half blocks which are usually supported a bit better. I'll close this for the time being and open a new issue for the raw tty case.

**Closed by fdehau** 2020-04-14 17:19 UTC
Labels: bug
